server:
  port: 8888
  
spring:
  
  cloud:
    config:
      server:
        git:
          uri: https://github.com/refforoberto/alura-micro-services-repo
          search-paths: fornecedor    
          default-label: main      
      